import{NextResponse}from"next/server"
import{createClient}from"@supabase/supabase-js"
import{allowRequest,clientIp,safeProjectInput,cleanText}from"@/lib/security"
const budgetMap:Record<string,[number|null,number|null]>={"< 10 000 €":[null,10000],"10 000–25 000 €":[10000,25000],"25 000–50 000 €":[25000,50000],"50 000 € et +":[50000,null],"À définir":[null,null]}
export async function POST(req:Request){try{
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return NextResponse.json({error:"Supabase n’est pas configuré."},{status:503})
 const ip=clientIp(req);if(!allowRequest(`project:${ip}`,5,30*60*1000))return NextResponse.json({error:"Trop de créations de projets. Réessayez plus tard."},{status:429})
 const raw=await req.json();const body=safeProjectInput(raw);if(!body.email||!body.email.includes("@"))return NextResponse.json({error:"Email valide requis."},{status:400})
 const supabase=createClient(url,key,{auth:{persistSession:false}});const password=crypto.randomUUID()+"aA1!";const{data:auth,error:authError}=await supabase.auth.signUp({email:body.email,password,options:{data:{first_name:body.firstname,last_name:body.lastname,phone:body.phone}}});if(authError||!auth.user)return NextResponse.json({error:authError?.message||"Création du compte impossible."},{status:400});if(!auth.session)return NextResponse.json({error:"Compte créé. La confirmation email Supabase est active; confirmez l’email avant de créer le projet."},{status:202})
 const[budget_min,budget_max]=budgetMap[body.budget]||[null,null];const richDetails=[body.housing&&`Logement: ${body.housing}`,body.level&&`Niveau / étage: ${body.level}`,body.floor&&`Sol actuel: ${body.floor}`,body.walls&&`Murs / supports: ${body.walls}`,body.utilities&&`Réseaux existants: ${body.utilities}`,body.globalWorks&&`Travaux globaux envisagés: ${body.globalWorks}`,body.access&&`Accès / contraintes chantier: ${body.access}`,body.details&&`Préférences: ${body.details}`,body.keep&&`À conserver: ${body.keep}`,body.change&&`À changer: ${body.change}`,body.constraints&&`Contraintes: ${body.constraints}`,body.usage&&`Usages: ${body.usage}`,body.avoid&&`À éviter: ${body.avoid}`,body.priority&&`Priorité: ${body.priority}`,body.dimensions&&`Dimensions: ${body.dimensions}`,body.aiBrief&&`Brief IA validé: ${body.aiBrief}`].filter(Boolean).join("\n").slice(0,12000)
 const{data:project,error:projectError}=await supabase.from("projects").insert({customer_id:auth.user.id,status:"draft",project_type:body.project,room_type:body.room,surface_m2:body.size?Number(body.size):null,style:body.style,details:richDetails,budget_min,budget_max,timing:body.timing,postcode:body.postcode}).select("id,reference").single();if(projectError||!project)return NextResponse.json({error:projectError?.message||"Création du projet impossible."},{status:400})
 const consentText="Je souhaite recevoir les actualités, inspirations et offres SpaceHome par email.";const{error:consentError}=await supabase.from("consents").insert([{project_id:project.id,customer_id:auth.user.id,purpose:"spacehome_marketing",granted:cleanText(raw?.marketing,10)==="yes",policy_version:"v1",consent_text:consentText}]);if(consentError)return NextResponse.json({error:consentError.message},{status:400})
 const res=NextResponse.json({projectId:project.id,reference:project.reference,partnerTransmission:false,projectSession:auth.session.access_token});res.cookies.set("sh_session",auth.session.access_token,{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:3600});res.cookies.set("sh_project",project.id,{httpOnly:true,secure:true,sameSite:"lax",path:"/",maxAge:3600});return res
}catch(e){console.error("project_error",e);return NextResponse.json({error:"Impossible de créer le projet pour le moment."},{status:500})}}
