export type Language = "en" | "fr" | "es"

export const translations = {
  en: {
    // Header
    nav: {
      howItWorks: "How It Works",
      gallery: "Gallery",
      pricing: "Pricing",
      contact: "Contact",
      startDesign: "Start Your Design",
    },
    // Hero
    hero: {
      tagline: "AI-Powered Interior Design",
      title: "Your dream space,",
      titleLine2: "designed in minutes",
      description:
        "Experience the future of interior design. Our AI creates personalized layouts for kitchens, living rooms, bedrooms, and more — validated by expert designers.",
      cta: "Design Your Space",
      viewGallery: "View Gallery",
      spacesDesigned: "Spaces Designed",
      clientRating: "Client Rating",
      expertReview: "Expert Review",
    },
    // How It Works
    howItWorks: {
      tagline: "The Process",
      title: "How It Works",
      description:
        "From inspiration to reality in three simple steps. Our AI handles the complexity while you focus on your vision.",
      step1Title: "Share Your Space",
      step1Desc:
        "Upload photos of your room or enter dimensions. Our AI analyzes your space to understand its unique characteristics.",
      step2Title: "AI Creates Your Design",
      step2Desc:
        "Our intelligent system generates personalized layouts based on your style preferences, budget, and spatial requirements.",
      step3Title: "Expert Validation",
      step3Desc:
        "A certified interior designer reviews your AI-generated plan, ensuring every detail is perfect before you receive your quote.",
      techTagline: "Our Technology",
      techTitle: "Intelligent design powered by advanced AI",
      techDesc:
        "Our proprietary AI has been trained on thousands of award-winning interior designs. It understands spatial relationships, ergonomics, and timeless design principles to create layouts that are both beautiful and functional.",
      feature1: "Analyzes natural light and traffic flow",
      feature2: "Optimizes storage and functionality",
      feature3: "Considers furniture placement and utilities",
      feature4: "Adapts to your preferred design style",
    },
    // Gallery
    gallery: {
      tagline: "Inspiration",
      title: "Design Gallery",
      description:
        "Explore designs created by our AI and refined by our expert team. Each space is a unique reflection of its owner.",
      categories: {
        all: "All Spaces",
        kitchen: "Kitchens",
        living: "Living Rooms",
        bedroom: "Bedrooms",
        dining: "Dining Rooms",
        furniture: "Custom Furniture",
      },
    },
    // Expert Validation
    expert: {
      tagline: "Human Expertise",
      title: "AI innovation meets expert craftsmanship",
      description:
        "Every design generated by our AI is reviewed and validated by a certified interior designer. This unique combination ensures you receive a plan that is not only beautiful but also practical, compliant with regulations, and tailored to your lifestyle.",
      quote: "The human touch makes all the difference.",
      quoteAuthor: "Marie Laurent, Lead Designer",
      item1Title: "Professional Review",
      item1Desc: "A certified designer examines every detail of your layout within 48 hours.",
      item2Title: "Personalized Adjustments",
      item2Desc: "Receive recommendations based on your specific needs and local requirements.",
      item3Title: "Direct Communication",
      item3Desc: "Schedule a consultation call to discuss your design with your assigned expert.",
    },
    // Pricing
    pricing: {
      tagline: "Pricing",
      title: "Simple, Transparent Pricing",
      description: "Choose the package that suits your project. All plans include our AI-powered design technology.",
      perProject: "per project",
      getStarted: "Get Started",
      taxNote: "All prices exclude applicable taxes. Need a custom solution?",
      contactUs: "Contact us",
      essential: {
        name: "Essential",
        description: "Perfect for single room transformations",
        features: [
          "AI-generated layout",
          "2 design variations",
          "Basic 3D visualization",
          "Material suggestions",
          "Email support",
        ],
      },
      premium: {
        name: "Premium",
        description: "Our most popular choice for complete spaces",
        features: [
          "Everything in Essential",
          "5 design variations",
          "Photorealistic renders",
          "Expert designer review",
          "Video consultation",
          "Detailed quote breakdown",
        ],
      },
      bespoke: {
        name: "Bespoke",
        description: "For whole-home or complex projects",
        features: [
          "Everything in Premium",
          "Unlimited revisions",
          "Dedicated designer",
          "Supplier coordination",
          "Project management support",
          "Priority turnaround",
        ],
      },
    },
    // Lead Capture
    lead: {
      tagline: "Start Your Project",
      title: "Begin your transformation today",
      description:
        "Share your space details and preferences. Our AI will analyze your requirements and a design expert will reach out with personalized recommendations within 48 hours.",
      benefit1: "Free initial consultation",
      benefit2: "No commitment required",
      benefit3: "Personalized design recommendations",
      benefit4: "Expert guidance throughout",
      testimonial:
        "The process was seamless. From the AI-generated concepts to the final design review, I felt guided every step of the way.",
      testimonialAuthor: "Charlotte Dubois",
      testimonialLocation: "Paris, France",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      phone: "Phone (Optional)",
      spaceType: "Space Type",
      spaceTypePlaceholder: "Select space type...",
      spaceTypes: {
        kitchen: "Kitchen",
        living: "Living Room",
        bedroom: "Bedroom",
        dining: "Dining Room",
        furniture: "Custom Furniture",
        multiple: "Multiple Rooms",
      },
      size: "Room Size",
      sizePlaceholder: "Select size...",
      sizes: {
        small: "Small (under 15m²)",
        medium: "Medium (15-25m²)",
        large: "Large (25-40m²)",
        xlarge: "Extra Large (over 40m²)",
      },
      style: "Preferred Style",
      stylePlaceholder: "Select style...",
      styles: {
        modern: "Modern Minimalist",
        traditional: "Classic Traditional",
        scandinavian: "Scandinavian",
        industrial: "Industrial",
        transitional: "Transitional",
        unsure: "Not sure yet",
      },
      budget: "Budget Range",
      budgetPlaceholder: "Select budget...",
      budgets: {
        "5-15k": "$5,000 - $15,000",
        "15-30k": "$15,000 - $30,000",
        "30-60k": "$30,000 - $60,000",
        "60k+": "$60,000+",
      },
      submit: "Request Your Design",
      submitting: "Submitting...",
      privacyNote: "By submitting, you agree to our Privacy Policy.",
      thankYou: "Thank you",
      thankYouDesc: "We've received your details. A design expert will contact you within 48 hours.",
    },
    // Footer
    footer: {
      description:
        "AI-powered interior design that combines cutting-edge technology with expert human craftsmanship. Creating beautiful spaces since 2024.",
      navigation: "Navigation",
      contact: "Contact",
      copyright: "© 2026 SpaceHome. All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
    },
  },
  fr: {
    // Header
    nav: {
      howItWorks: "Comment ça marche",
      gallery: "Galerie",
      pricing: "Tarifs",
      contact: "Contact",
      startDesign: "Commencer",
    },
    // Hero
    hero: {
      tagline: "Design d'intérieur propulsé par l'IA",
      title: "Votre espace rêvé,",
      titleLine2: "conçu en quelques minutes",
      description:
        "Découvrez le futur du design d'intérieur. Notre IA crée des aménagements personnalisés pour cuisines, salons, chambres et plus — validés par des experts.",
      cta: "Concevoir votre espace",
      viewGallery: "Voir la galerie",
      spacesDesigned: "Espaces conçus",
      clientRating: "Évaluation clients",
      expertReview: "Révision expert",
    },
    // How It Works
    howItWorks: {
      tagline: "Le processus",
      title: "Comment ça marche",
      description:
        "De l'inspiration à la réalité en trois étapes simples. Notre IA gère la complexité pendant que vous vous concentrez sur votre vision.",
      step1Title: "Partagez votre espace",
      step1Desc:
        "Téléchargez des photos de votre pièce ou entrez les dimensions. Notre IA analyse votre espace pour comprendre ses caractéristiques uniques.",
      step2Title: "L'IA crée votre design",
      step2Desc:
        "Notre système intelligent génère des aménagements personnalisés selon vos préférences de style, budget et besoins spatiaux.",
      step3Title: "Validation par un expert",
      step3Desc:
        "Un designer d'intérieur certifié examine votre plan généré par l'IA, s'assurant que chaque détail est parfait avant de recevoir votre devis.",
      techTagline: "Notre technologie",
      techTitle: "Design intelligent propulsé par l'IA avancée",
      techDesc:
        "Notre IA propriétaire a été formée sur des milliers de designs d'intérieur primés. Elle comprend les relations spatiales, l'ergonomie et les principes de design intemporels pour créer des aménagements beaux et fonctionnels.",
      feature1: "Analyse la lumière naturelle et la circulation",
      feature2: "Optimise le rangement et la fonctionnalité",
      feature3: "Considère le placement des meubles et utilités",
      feature4: "S'adapte à votre style préféré",
    },
    // Gallery
    gallery: {
      tagline: "Inspiration",
      title: "Galerie de designs",
      description:
        "Explorez les designs créés par notre IA et affinés par notre équipe d'experts. Chaque espace est le reflet unique de son propriétaire.",
      categories: {
        all: "Tous les espaces",
        kitchen: "Cuisines",
        living: "Salons",
        bedroom: "Chambres",
        dining: "Salles à manger",
        furniture: "Mobilier sur mesure",
      },
    },
    // Expert Validation
    expert: {
      tagline: "Expertise humaine",
      title: "L'innovation IA rencontre l'artisanat expert",
      description:
        "Chaque design généré par notre IA est revu et validé par un designer d'intérieur certifié. Cette combinaison unique garantit un plan non seulement beau mais aussi pratique, conforme aux réglementations et adapté à votre style de vie.",
      quote: "La touche humaine fait toute la différence.",
      quoteAuthor: "Marie Laurent, Designer principale",
      item1Title: "Révision professionnelle",
      item1Desc: "Un designer certifié examine chaque détail de votre aménagement sous 48 heures.",
      item2Title: "Ajustements personnalisés",
      item2Desc: "Recevez des recommandations basées sur vos besoins spécifiques et exigences locales.",
      item3Title: "Communication directe",
      item3Desc: "Planifiez un appel de consultation pour discuter de votre design avec votre expert assigné.",
    },
    // Pricing
    pricing: {
      tagline: "Tarifs",
      title: "Tarification simple et transparente",
      description:
        "Choisissez le forfait qui correspond à votre projet. Tous les plans incluent notre technologie de design IA.",
      perProject: "par projet",
      getStarted: "Commencer",
      taxNote: "Tous les prix excluent les taxes applicables. Besoin d'une solution personnalisée ?",
      contactUs: "Contactez-nous",
      essential: {
        name: "Essentiel",
        description: "Parfait pour les transformations de pièce unique",
        features: [
          "Aménagement généré par IA",
          "2 variations de design",
          "Visualisation 3D basique",
          "Suggestions de matériaux",
          "Support par email",
        ],
      },
      premium: {
        name: "Premium",
        description: "Notre choix le plus populaire pour des espaces complets",
        features: [
          "Tout dans Essentiel",
          "5 variations de design",
          "Rendus photoréalistes",
          "Révision par expert designer",
          "Consultation vidéo",
          "Devis détaillé",
        ],
      },
      bespoke: {
        name: "Sur mesure",
        description: "Pour des projets de maison entière ou complexes",
        features: [
          "Tout dans Premium",
          "Révisions illimitées",
          "Designer dédié",
          "Coordination fournisseurs",
          "Support gestion de projet",
          "Délai prioritaire",
        ],
      },
    },
    // Lead Capture
    lead: {
      tagline: "Commencer votre projet",
      title: "Commencez votre transformation aujourd'hui",
      description:
        "Partagez les détails de votre espace et vos préférences. Notre IA analysera vos besoins et un expert en design vous contactera avec des recommandations personnalisées sous 48 heures.",
      benefit1: "Consultation initiale gratuite",
      benefit2: "Aucun engagement requis",
      benefit3: "Recommandations de design personnalisées",
      benefit4: "Accompagnement expert tout au long",
      testimonial:
        "Le processus était fluide. Des concepts générés par l'IA à la révision finale du design, je me suis sentie guidée à chaque étape.",
      testimonialAuthor: "Charlotte Dubois",
      testimonialLocation: "Paris, France",
      firstName: "Prénom",
      lastName: "Nom",
      email: "Email",
      phone: "Téléphone (Optionnel)",
      spaceType: "Type d'espace",
      spaceTypePlaceholder: "Sélectionner le type...",
      spaceTypes: {
        kitchen: "Cuisine",
        living: "Salon",
        bedroom: "Chambre",
        dining: "Salle à manger",
        furniture: "Mobilier sur mesure",
        multiple: "Plusieurs pièces",
      },
      size: "Taille de la pièce",
      sizePlaceholder: "Sélectionner la taille...",
      sizes: {
        small: "Petite (moins de 15m²)",
        medium: "Moyenne (15-25m²)",
        large: "Grande (25-40m²)",
        xlarge: "Très grande (plus de 40m²)",
      },
      style: "Style préféré",
      stylePlaceholder: "Sélectionner le style...",
      styles: {
        modern: "Moderne minimaliste",
        traditional: "Classique traditionnel",
        scandinavian: "Scandinave",
        industrial: "Industriel",
        transitional: "Transitionnel",
        unsure: "Pas encore sûr",
      },
      budget: "Fourchette de budget",
      budgetPlaceholder: "Sélectionner le budget...",
      budgets: {
        "5-15k": "5 000€ - 15 000€",
        "15-30k": "15 000€ - 30 000€",
        "30-60k": "30 000€ - 60 000€",
        "60k+": "60 000€+",
      },
      submit: "Demander votre design",
      submitting: "Envoi en cours...",
      privacyNote: "En soumettant, vous acceptez notre Politique de confidentialité.",
      thankYou: "Merci",
      thankYouDesc: "Nous avons reçu vos informations. Un expert en design vous contactera sous 48 heures.",
    },
    // Footer
    footer: {
      description:
        "Design d'intérieur propulsé par l'IA qui combine technologie de pointe et artisanat humain expert. Créant de beaux espaces depuis 2024.",
      navigation: "Navigation",
      contact: "Contact",
      copyright: "© 2026 SpaceHome. Tous droits réservés.",
      privacy: "Politique de confidentialité",
      terms: "Conditions d'utilisation",
    },
  },
  es: {
    // Header
    nav: {
      howItWorks: "Cómo funciona",
      gallery: "Galería",
      pricing: "Precios",
      contact: "Contacto",
      startDesign: "Comenzar",
    },
    // Hero
    hero: {
      tagline: "Diseño de interiores con IA",
      title: "Tu espacio soñado,",
      titleLine2: "diseñado en minutos",
      description:
        "Experimenta el futuro del diseño de interiores. Nuestra IA crea diseños personalizados para cocinas, salas, dormitorios y más — validados por diseñadores expertos.",
      cta: "Diseña tu espacio",
      viewGallery: "Ver galería",
      spacesDesigned: "Espacios diseñados",
      clientRating: "Calificación",
      expertReview: "Revisión experta",
    },
    // How It Works
    howItWorks: {
      tagline: "El proceso",
      title: "Cómo funciona",
      description:
        "De la inspiración a la realidad en tres simples pasos. Nuestra IA maneja la complejidad mientras tú te enfocas en tu visión.",
      step1Title: "Comparte tu espacio",
      step1Desc:
        "Sube fotos de tu habitación o ingresa las dimensiones. Nuestra IA analiza tu espacio para entender sus características únicas.",
      step2Title: "La IA crea tu diseño",
      step2Desc:
        "Nuestro sistema inteligente genera diseños personalizados basados en tus preferencias de estilo, presupuesto y requisitos espaciales.",
      step3Title: "Validación experta",
      step3Desc:
        "Un diseñador de interiores certificado revisa tu plan generado por IA, asegurando que cada detalle sea perfecto antes de recibir tu cotización.",
      techTagline: "Nuestra tecnología",
      techTitle: "Diseño inteligente impulsado por IA avanzada",
      techDesc:
        "Nuestra IA propietaria ha sido entrenada con miles de diseños de interiores premiados. Entiende relaciones espaciales, ergonomía y principios de diseño atemporales para crear diseños hermosos y funcionales.",
      feature1: "Analiza luz natural y flujo de tráfico",
      feature2: "Optimiza almacenamiento y funcionalidad",
      feature3: "Considera ubicación de muebles y utilidades",
      feature4: "Se adapta a tu estilo preferido",
    },
    // Gallery
    gallery: {
      tagline: "Inspiración",
      title: "Galería de diseños",
      description:
        "Explora diseños creados por nuestra IA y refinados por nuestro equipo experto. Cada espacio es un reflejo único de su propietario.",
      categories: {
        all: "Todos los espacios",
        kitchen: "Cocinas",
        living: "Salas de estar",
        bedroom: "Dormitorios",
        dining: "Comedores",
        furniture: "Muebles a medida",
      },
    },
    // Expert Validation
    expert: {
      tagline: "Experiencia humana",
      title: "Innovación IA con artesanía experta",
      description:
        "Cada diseño generado por nuestra IA es revisado y validado por un diseñador de interiores certificado. Esta combinación única asegura un plan no solo hermoso sino también práctico, conforme a regulaciones y adaptado a tu estilo de vida.",
      quote: "El toque humano hace toda la diferencia.",
      quoteAuthor: "Marie Laurent, Diseñadora principal",
      item1Title: "Revisión profesional",
      item1Desc: "Un diseñador certificado examina cada detalle de tu diseño en 48 horas.",
      item2Title: "Ajustes personalizados",
      item2Desc: "Recibe recomendaciones basadas en tus necesidades específicas y requisitos locales.",
      item3Title: "Comunicación directa",
      item3Desc: "Programa una llamada de consulta para discutir tu diseño con tu experto asignado.",
    },
    // Pricing
    pricing: {
      tagline: "Precios",
      title: "Precios simples y transparentes",
      description:
        "Elige el paquete que se adapte a tu proyecto. Todos los planes incluyen nuestra tecnología de diseño con IA.",
      perProject: "por proyecto",
      getStarted: "Comenzar",
      taxNote: "Todos los precios excluyen impuestos aplicables. ¿Necesitas una solución personalizada?",
      contactUs: "Contáctanos",
      essential: {
        name: "Esencial",
        description: "Perfecto para transformaciones de una habitación",
        features: [
          "Diseño generado por IA",
          "2 variaciones de diseño",
          "Visualización 3D básica",
          "Sugerencias de materiales",
          "Soporte por email",
        ],
      },
      premium: {
        name: "Premium",
        description: "Nuestra opción más popular para espacios completos",
        features: [
          "Todo en Esencial",
          "5 variaciones de diseño",
          "Renders fotorrealistas",
          "Revisión de diseñador experto",
          "Consulta por video",
          "Desglose detallado de cotización",
        ],
      },
      bespoke: {
        name: "A medida",
        description: "Para proyectos de casa completa o complejos",
        features: [
          "Todo en Premium",
          "Revisiones ilimitadas",
          "Diseñador dedicado",
          "Coordinación de proveedores",
          "Soporte de gestión de proyecto",
          "Entrega prioritaria",
        ],
      },
    },
    // Lead Capture
    lead: {
      tagline: "Comienza tu proyecto",
      title: "Comienza tu transformación hoy",
      description:
        "Comparte los detalles de tu espacio y preferencias. Nuestra IA analizará tus requisitos y un experto en diseño te contactará con recomendaciones personalizadas en 48 horas.",
      benefit1: "Consulta inicial gratuita",
      benefit2: "Sin compromiso requerido",
      benefit3: "Recomendaciones de diseño personalizadas",
      benefit4: "Guía experta durante todo el proceso",
      testimonial:
        "El proceso fue perfecto. Desde los conceptos generados por IA hasta la revisión final del diseño, me sentí guiada en cada paso.",
      testimonialAuthor: "Charlotte Dubois",
      testimonialLocation: "París, Francia",
      firstName: "Nombre",
      lastName: "Apellido",
      email: "Email",
      phone: "Teléfono (Opcional)",
      spaceType: "Tipo de espacio",
      spaceTypePlaceholder: "Seleccionar tipo...",
      spaceTypes: {
        kitchen: "Cocina",
        living: "Sala de estar",
        bedroom: "Dormitorio",
        dining: "Comedor",
        furniture: "Muebles a medida",
        multiple: "Varias habitaciones",
      },
      size: "Tamaño de la habitación",
      sizePlaceholder: "Seleccionar tamaño...",
      sizes: {
        small: "Pequeña (menos de 15m²)",
        medium: "Mediana (15-25m²)",
        large: "Grande (25-40m²)",
        xlarge: "Extra grande (más de 40m²)",
      },
      style: "Estilo preferido",
      stylePlaceholder: "Seleccionar estilo...",
      styles: {
        modern: "Moderno minimalista",
        traditional: "Clásico tradicional",
        scandinavian: "Escandinavo",
        industrial: "Industrial",
        transitional: "Transicional",
        unsure: "Aún no estoy seguro",
      },
      budget: "Rango de presupuesto",
      budgetPlaceholder: "Seleccionar presupuesto...",
      budgets: {
        "5-15k": "$5,000 - $15,000",
        "15-30k": "$15,000 - $30,000",
        "30-60k": "$30,000 - $60,000",
        "60k+": "$60,000+",
      },
      submit: "Solicitar tu diseño",
      submitting: "Enviando...",
      privacyNote: "Al enviar, aceptas nuestra Política de privacidad.",
      thankYou: "Gracias",
      thankYouDesc: "Hemos recibido tus datos. Un experto en diseño te contactará en 48 horas.",
    },
    // Footer
    footer: {
      description:
        "Diseño de interiores con IA que combina tecnología de vanguardia con artesanía humana experta. Creando espacios hermosos desde 2024.",
      navigation: "Navegación",
      contact: "Contacto",
      copyright: "© 2026 SpaceHome. Todos los derechos reservados.",
      privacy: "Política de privacidad",
      terms: "Términos de servicio",
    },
  },
}

export function getTranslation(lang: Language) {
  return translations[lang]
}
